Updated lab check scripts to reflect modified numbering.

diff --git a/lab9-check-1 b/lab9-check-1
--- a/lab9-check-1
+++ b/lab9-check-1
@@ -1,87 +1,162 @@
 #!/bin/bash
 
-# ./lab9-check-1.bash
+# lab9-check-1
 
 # Author:  Murray Saul
-# Date:    June 7, 2016
-# Edited by: Peter Callaghan
-# Date: Sept 26, 2021
+# Date:    February 18, 2021
+# Modified by:	Jason Carman
+# Modified:	September 14, 2026
 #
-# Edited by: Brian Gray 
-# For new debian labs Fall 2023
+# Purpose: Check that user correctly issued sed Linux commands
+#          on their matrix server. If the errors, then the
+#          checking script will provide feedback to correct the problem.
+#          If no errors, then a congratulatory message will be displayed
+#          so that the user can proceed to the next section.
 #
-# Edited by: Jason Carman
-# For Ubuntu 24.04 in OSL645
-# Date: November 1, 2024
+# License: LGPL version 3
+# Link:    https://www.gnu.org/licenses/lgpl.html
+#
 
-#
-# Purpose: Check that students correctly managed user and group accounts
-#          when performing this lab, check that students have properly
-#          managed services, and created a shell script to work like
-#          a Linux command to automate creation of multiple user
-#          accounts (user data stored in a text-file).
+logfile=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)/Documents/$0_output.txt
 
 # Function to indicate OK (in green) if check is true; otherwise, indicate
 # WARNING (in red) if check is false and end with false exit status
-suser=${SUDO_USER:-$USER}
-logfile=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)/Documents/lab9-check-1_output.txt
 
 function check(){
 
   if eval $1; then
      echo -e "\e[0;32mOK\e[m"
   else
-     echo
-     echo
      echo -e "\e[0;31mWARNING\e[m"
-     echo
-     echo
-     echo $2
+     echo 
+     echo $2 
      echo
      exit 1
   fi
 
 } # end of check() function
 
+# Set shell shell history
+HISTFILE=~/.bash_history
+set -o history
+
 clear  # Clear the screen
 
-# Make certain user is logged in as root
-if [ $(whoami) != "root" ]; then
-  echo "Note: You are required to run this program as root. Use sudo"
-  exit 1
+# Make certain user is in the home directory
+
+if [ $PWD != $HOME ]; then
+   echo -e "\033[1mERROR:\033[0m"
+   echo
+   echo "You are NOT located in your HOME directory."
+   echo -e "(i.e. \033[1m$HOME\033[0m )"
+   echo
+   echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
+   echo -e "and confirm that you are"
+   echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
+   echo "and re-run this checking script."
+   echo
+   echo
+
+   exit 1
 fi
 
 # System information gathering
-echo "OSL645 Lab 9 Check 1 Script" > $logfile
+echo "OSL645 Lab 8 Check 1 Script" > $logfile
+
+# Add a unique identifier to the logfile
+read -p "Please enter your Seneca ID (ie jmcarman): " user
+echo "Unique Identifer: $(echo $user | sha256sum)" | tee -a $logfile
+echo "------------------------------------" | tee -a $logfile
+
+# Start checking lab
 echo | tee -a $logfile
 echo "CHECKING YOUR LAB 9 WORK:" | tee -a $logfile
-echo | tee -a $logfile
+echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
+echo
 
-# Check osl645_2 user created
-echo "Checking that osl645_2 user created: " | tee -a $logfile
-check "grep -isq \"osl645_2\" /etc/passwd" "This program did NOT detect the user \"osl645_2\" in the \"/etc/passwd\" file. Please create this user, complete this lab, and re-run this checking script." | tee -a $logfile
+# Check directory "sed" created in home directory
+echo -n "Checking \"sed\" directory has been created in your home directory: " | tee -a $logfile
+check "test -d $HOME/sed" "The directory pathname \"$HOME/sed\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"sed\" in your home directory and re-run this checking script" | tee -a $logfile
 
-# Check osl645_1 user removed
-echo -n "Checking that osl645_1 user removed: "
-check "! grep -isq \"osl645_1\" /etc/passwd" "This program detected the user \"osl645_1\" in the \"/etc/passwd\" file, when that user should have been removed. Please remove this user, complete this lab, and re-run this checking script."
+# Check that data.txt file was copied to your "sed" directory
+echo -n "Checking \"data.txt\" file was copied to the \"sed\" directory: " | tee -a $logfile
+check "test -f $HOME/sed/data.txt" "The file pathname \"$HOME/sed/data.txt\" does NOT exist. Change to ~/bin and issue git pull to properly download this file. Copy it to your ~/sed directory and re-run this checking script" | tee -a $logfile
 
-# Check foobar.txt created in /etc/skel directory
-echo "Checking that \"/etc/skel\" directory contains the file called \"foobar.txt\":" | tee -a $logfile
-check "ls /etc/skel | grep -isq \"foobar.txt\"" "This program did NOT detect the file called \"foobar.txt\" in the \"/etc/skel\" directory. Please create this file, remove the user ops245_2, and then create that user to see the \"foobar.txt\" file automatically created in that user's home directory upon the creation of this user. Complete this lab, and re-run this checking script." | tee -a $logfile
+# Check ~/sed/sed-1.txt file exists
+echo -n "Checking \"$HOME/sed/sed-1.txt\" file exists: " | tee -a $logfile
+check "test -f $HOME/sed/sed-1.txt" "The text file pathname \"$HOME/sed/sed-1.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile
 
-# Check group created with name "welcome"
-echo "Checking that a group name \"welcome\" is contained in the file \"/etc/group\": " | tee -a $logfile
-check "grep -isq \"welcome\" /etc/group" "This program did NOT detect the group name \"welcome\" in the \"/etc/group\" file. Please remove the group, and correctly add the group with the correct GID, complete the lab (with secondary users added), and re-run this checking script." | tee -a $logfile
+# Check ~/sed/sed-1.txt file contains correct results
+echo -n "Checking \"$HOME/sed/sed-1.txt\" file contains correct results: " | tee -a $logfile
+sed -n 'p' $HOME/sed/data.txt > /tmp/temp.$$
+check "diff $HOME/sed/sed-1.txt /tmp/temp.$$ > /dev/null" "The \"$HOME/sed/sed-1.txt\" does NOT  contain the correct results from issuing the pipeline command. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile
+rm /tmp/temp.$$ 2> /dev/null
 
-# Check user noobie removed
-echo "Checking that \"noobie\" user was removed: " | tee -a $logfile
-check "! grep -isq \"noobie\" /etc/passwd" "This program did NOT detect the user name \"noobie\" was removed. Remove this user account, and re-run this checking script." | tee -a $logfile
+# Check ~/sed/sed-2.txt file exists
+echo -n "Checking \"$HOME/sed/sed-2.txt\" file exists: " | tee -a $logfile
+check "test -f $HOME/sed/sed-2.txt" "The text file pathname \"$HOME/sed/sed-2.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile
 
-# Check ssh service started and enabled
-echo "Checking that ssh service started and enabled: " | tee -a $logfile
-check "systemctl status ssh | grep -iqs \"active\" && systemctl status ssh | grep -iqs \"enabled\"" "This program did NOT detect that the ssh service has \"started\" and/or is \"enabled\". Use systemctl to start and enable the ssh service, and re-run this checking script." | tee -a $logfile
+# Check ~/sed/sed-2.txt file contains correct results
+echo -n "Checking \"$HOME/sed/sed-2.txt\" file contains correct results: " | tee -a $logfile
+sed -n '1 p' $HOME/sed/data.txt > /tmp/temp.$$
+check "diff $HOME/sed/sed-2.txt /tmp/temp.$$ > /dev/null" "The \"$HOME/sed/sed-2.txt\" does NOT  contain the correct results from issuing the pipeline command. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile
+rm /tmp/temp.$$ 2> /dev/null
 
-warningcount=`grep -c "WARNING" $logfile`
+# Check ~/sed/sed-3.txt file exists
+echo -n "Checking \"$HOME/sed/sed-3.txt\" file exists: " | tee -a $logfile
+check "test -f $HOME/sed/sed-3.txt" "The text file pathname \"$HOME/sed/sed-3.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile
+
+# Check ~/sed/sed-3.txt file contains correct results
+echo -n "Checking \"$HOME/sed/sed-3.txt\" file contains correct results: " | tee -a $logfile
+sed -n '2,5 p' $HOME/sed/data.txt  > /tmp/temp.$$
+check "diff $HOME/sed/sed-3.txt /tmp/temp.$$ > /dev/null" "The \"$HOME/sed/sed-3.txt\" does NOT  contain the correct results from issuing the pipeline command. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile
+rm /tmp/temp.$$ 2> /dev/null
+
+# Check ~/sed/sed-4.txt file exists
+echo -n "Checking \"$HOME/sed/sed-4.txt\" file exists: " | tee -a $logfile
+check "test -f $HOME/sed/sed-4.txt" "The text file pathname \"$HOME/sed/sed-4.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile
+
+# Check ~/sed/sed-4.txt file contains correct results
+echo -n "Checking \"$HOME/sed/sed-4.txt\" file contains correct results: " | tee -a $logfile
+sed '2,5 s/TUTORIAL/LESSON/g' $HOME/sed/data.txt > /tmp/temp.$$
+check "diff $HOME/sed/sed-4.txt /tmp/temp.$$ > /dev/null" "The \"$HOME/sed/sed-4.txt\" does NOT  contain the correct results from issuing the pipeline command. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile
+rm /tmp/temp.$$ 2> /dev/null
+
+# Check ~/sed/sed-5.txt file exists
+echo -n "Checking \"$HOME/sed/sed-5.txt\" file exists: " | tee -a $logfile
+check "test -f $HOME/sed/sed-5.txt" "The text file pathname \"$HOME/sed/sed-5.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile
+
+# Check ~/sed/sed-5.txt file contains correct results
+echo -n "Checking \"$HOME/sed/sed-5.txt\" file contains correct results: " | tee -a $logfile
+sed '11 q' $HOME/sed/data.txt > /tmp/temp.$$
+check "diff $HOME/sed/sed-5.txt /tmp/temp.$$ > /dev/null" "The \"$HOME/sed/sed-5.txt\" does NOT  contain the correct results from issuing the pipeline command. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile
+rm /tmp/temp.$$ 2> /dev/null
+
+# Check ~/sed/sed-6.txt file exists
+echo -n "Checking \"$HOME/sed/sed-6.txt\" file exists: " | tee -a $logfile
+check "test -f $HOME/sed/sed-6.txt" "The text file pathname \"$HOME/sed/sed-6.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile
+
+# Check ~/sed/sed-6.txt file contains correct results
+echo -n "Checking \"$HOME/sed/sed-6.txt\" file contains correct results: " | tee -a $logfile
+sed -n '/^The/ p' $HOME/sed/data.txt > /tmp/temp.$$
+check "diff $HOME/sed/sed-6.txt /tmp/temp.$$ > /dev/null" "The \"$HOME/sed/sed-6.txt\" does NOT  contain the correct results from issuing the pipeline command. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile
+rm /tmp/temp.$$ 2> /dev/null
+
+# Check ~/sed/sed-7.txt file exists
+echo -n "Checking \"$HOME/sed/sed-7.txt\" file exists: " | tee -a $logfile
+check "test -f $HOME/sed/sed-7.txt" "The text file pathname \"$HOME/sed/sed-7.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile
+
+# Check ~/sed/sed-7.txt file contains correct results
+echo -n "Checking \"$HOME/sed/sed-7.txt\" file contains correct results: " | tee -a $logfile
+sed -n '/d$/ p' $HOME/sed/data.txt > /tmp/temp.$$
+check "diff $HOME/sed/sed-7.txt /tmp/temp.$$ > /dev/null" "The \"$HOME/sed/sed-7.txt\" does NOT  contain the correct results from issuing the pipeline command. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile
+rm /tmp/temp.$$ 2> /dev/null
+
+# Check ~/sed/sed-8.txt file exists
+echo -n "Checking \"$HOME/sed/sed-8.txt\" file exists: " | tee -a $logfile
+check "test -f $HOME/sed/sed-8.txt" "The text file pathname \"$HOME/sed/sed-8.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script"
+
+warningcount=$(grep -c "WARNING" $logfile)
 
 echo | tee -a $logfile
 echo | tee -a $logfile
@@ -89,8 +164,8 @@ echo | tee -a $logfile
 if [ $warningcount == 0 ]; then
   echo "Congratulations!" | tee -a $logfile
   echo | tee -a $logfile
-  echo "You have successfully completed Lab 9 - Check 1" | tee -a $logfile
-  echo "1. Show the output of this script to your OSL645 professor." | tee -a $logfile
+  echo "You have successfully completed $(echo $0)" | tee -a $logfile
+  echo "1. Show the output of this script to your OPS145 professor." | tee -a $logfile
   echo "2. A copy of this script output has been created at $logfile." | tee -a $logfile
   echo
 else
